version: '3'

services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"

  cas-web:
    image: "kaiwinter/docker-java8-maven"
    ports:
      - "8080:8080"
    volumes:
      - ./cas:/cas-web
    working_dir: /cas-web
    command: mvn clean package -DskipTests
    depends_on:
      - redis
